version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: school123
      MYSQL_DATABASE: school_db

  backend:
    build: ./server
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: school123
      DB_NAME: school_db
      PORT: 5000
    depends_on:
      - mysql

  frontend:
    build: ./client
    restart: always
    ports:
      - "3000:80"   # Change from "80:80" to "3000:80"
    depends_on:
      - backend
